source/12_django/myproject/article/urls.py
from django.urls import path
from . import views
# 기사목록 /article/          article:list
# 기사추가 /article/new/      article:new
# 기사상세 /article/1/detail  article:detail
# 기사수정 /article/1/edit/   article:edit
# 기사삭제 /article/1/delete/ article:delete
# v2. 검색기능 O, 파일첨부
from .views import ArticleListView, ArticleCreateView, ArticleDetailView
from .views import ArticleUpdateView, ArticleDeleteView
app_name = "article"
urlpatterns = [
  path("", ArticleListView.as_view(), name="list"),
  path("new/", ArticleCreateView.as_view(), name="new"),
  path("<int:pk>/detail", ArticleDetailView.as_view(), name="detail"),
  path("<int:pk>/edit/", ArticleUpdateView.as_view() , name="edit"),
  path("<int:pk>/delete", ArticleDeleteView.as_view(), name="delete")
]

source/12_django/myproject/blog/urls.py
# blog/urls.py
# blog/~ 요청 경로로 요청이 들어왔을 경우 본 모듈
from django.urls import path
from . import views
app_name = "blog"
urlpatterns = [
    path("", views.list, name="list"), # /blog 요청 -> blog:list
    path("<int:post_id>/", views.detail, name="detail"), # /blog/2
]

source/12_django/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", lambda request : redirect("file:upload_file")),
    path("blog/", include("blog.urls")),
    path("book/", include("book.urls")),
    path("article/", include("article.urls")),
    path("file/", include("filetest.urls")),
    path("accounts/", include("accounts.urls")),
]
# 장고는 static은 자동연결. media는 개발자가 url과 root경로를 연결
from django.conf.urls.static import static
from . import settings
urlpatterns += static(settings.MEDIA_URL,   # /media
                    document_root=settings.MEDIA_ROOT)  # BASE_DIR/_media저장

source/12_django/myproject/blog/models.py
from django.db import models
import re
from django.forms import ValidationError
from django.utils import timezone
# Create your models here.
REGION_CHOICE = ( # pdf 19p참조 ("db에 입력될 값", "form태그에 출력될 값")
  ("Europe","유럽"),
  ("Asia", "아시아"),
  ("Oceania","오세아니아"),
  ("America","아메리카"),
  ("Africa", "아프리카"),
)
def lnglat_validator(value):
  if not re.match(r'(\d+\.?\d*),(\d+\.?\d*)', value):
    raise ValidationError("경도 위도 타입이 아닙니다. ex.125.2,38")
  
class Tag(models.Model):
  name = models.CharField(max_length=50, unique=True)
  def __init__(self):
    return self.name

class Post(models.Model): #테이블명 : blog_post
  # id = models.AutoField(primary_key=True) PK가 없을 경우 자동 생성
  title = models.CharField(verbose_name="제목", # form의 라벨
                          max_length=100, # 최대 문자 길이 반드시 지정 VARCHAR(100)
                          help_text="기사 제목입니다. 100자 내외로 입력하세요")
  content = models.TextField("본문") # 최대 문자 길이 제한 없음 CLOB타입, TEXT타입
  create_at = models.DateField(auto_now_add=True) # 등록일 자동 저장
  update_at = models.DateTimeField(auto_now=True) # 등록/수정 날짜와시간 자동 저장
  region = models.CharField(verbose_name="지역",
                            max_length=100,
                            choices= REGION_CHOICE,
                            default="Asia")
  lnglat = models.CharField(verbose_name="경,위도",
                            max_length=100,
                            blank=True,
                            null=True, 
                            help_text="경도,위도 포맷 ex.37,125.5",
                            validators=[lnglat_validator])
  url = models.URLField(blank=True, null=True)
  tags = models.ManyToManyField(Tag, blank=True)

  def __str__(self): # 테이블의 한 레코드에 대해 작업 대상
    updated = timezone.localtime(self.update_at).strftime("%Y-%m-%d %H:%M")
    return "{}.제목:{} - {}작성. {}최종수정".format(self.id,
                                        self.title,
                                        self.create_at,
                                        updated)
  class Meta: # 테이블의 모든 레코드에 대해 작업 대상
    # db_table = "blog_post"
    ordering = ['-update_at']
    unique_together = [('title', 'content')] # 같은 title과 content 불가

class Comment(models.Model): # 테이블명 : blog_comment (Post의 댓글 내용)=> post:comment = 1:N
  # id = models.AutoField(primary_key=True)
  post = models.ForeignKey(Post, on_delete=models.CASCADE) # post내용을 delete일 경유 댓글도 자동 삭제
  author = models.CharField(verbose_name="댓글쓴이", max_length=20, null=True, blank=True)
  message = models.TextField(verbose_name="댓글")
  create_at = models.DateField(auto_now_add=True)
  update_at = models.DateTimeField(auto_now=True)
  def __str__(self):
    updated = timezone.localtime(self.update_at).strftime("%Y-%m-%d %p %I:%M") # PM 1:30
    updated = updated.replace("AM", "오전").replace("PM", "오후")
    return "{}글의 댓글 {} (by {}, at {})".format(self.post.pk,
                                              self.message,
                                              self.author,
                                              updated)
  
  class Meta:
    ordering = ['-update_at']
    unique_together = [('post', 'author', 'message')]

source/12_django/myproject/blog/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Post
# Create your views here.
def list(request):
    print("request:user", request.user) # 로그인전 : AnonymousUser객체/로그인후:로그인한 User객체
    post_list = Post.objects.all()
    return render(request, "blog/index.html", {"post_list":post_list, 
                                            # "user":request.user
                                            })
def detail(request, post_id):
    try:
        post = Post.objects.get(pk=post_id)
        return render(request, "blog/detail.html", {"post":post})
    except:
        messages.error(request, f"{post_id}번 글이 없습니다")
        return redirect("blog:list")

source/12_django/myproject/blog/templates/blog/detail.html
{% extends "base.html" %}
{% block title %}{{post.id}}번 post{% endblock %}
{% block content %}
  {% if post %}
    <h2>{{post.id}}.{{post.title}}</h2>
    <p>
      {{post.content}}<br>
      {{post.content | truncatechars:20 }}<br>
      <span>{{post.create_at | date:"Y-m-d"}}</span>
      <span>{{post.update_at | date:"y-m-d A h:i:s"}}</span>
      <span>{{post.update_at | date:"y-m-d H:i:s"}}</span>
    </p>
    <h4>댓글 : {{ post.comment_set.all | length }}개</h4>
    {% for comment in post.comment_set.all %}
      <h6>
        {{comment.message}}
        <span>by {{comment.author}} at {{comment.update_at | date:'y-m-d H:i'}}</span>
      </h6>
    {% endfor %}
    {% for tag in post.tags.all %}
      #<b>{{tag.name}}</b>
    {% empty %}
      <h6>등록된 태그가 없습니다</h6>
    {% endfor %}
    <br>
  {% else %}
    <p>No post</p>
  {% endif %}
  <button class="btn btn-primary"
      onclick="location='{% url 'blog:list' %}'">
    목록
  </button>
{% endblock %}

source/12_django/myproject/blog/templates/blog/index.html
{% extends "base.html" %}
{% block title %}post list{% endblock %}
{% block content %}
<!-- Django 메시지를 Bootstrap Alert로 표시 -->
  {% if messages %}
    {% for message in messages %}
      {% if message.tags == 'success' %}
        <div class="alert alert-success alert-dismissible fade show">
          ✅ {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
      {% elif message.tags == 'error' %}
        <div class="alert alert-danger alert-dismissible fade show">
          ❌{{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
      {% endif %}
    {% endfor %}
  {% endif %}


{% if post_list %}
    <ul>
    {% for post in post_list %}
      <li>
        {% comment %} <a href="/blog/{{post.id}}/">{{post.id}}.{{post.title}}</a>{% endcomment %}
        <a href="{% url 'blog:detail' post.id %}">{{post.id}}.{{post.title}}</a> 
        {{post.create_at}} post함 {{post.update_at|date:"y/m/d H:i"}} 최종수정
        {{post.update_at|date:"y/m/d a h:i"}}
        {% if post.comment_set.count %}
          <b>[{{post.comment_set.count}}]</b>
        {% endif %}
      </li>
    {% endfor %}
    </ul>
{% endif %}
{% endblock %}